### ISSUE TITLE
JCMT sdf image resulting a crash

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#472] opened 2020-03-18 11:25 UTC
sdf image should not appear on the file list and it is true with the following example (zipped)
[s20160910_00078_450_reduced.sdf.zip](https://github.com/CARTAvis/carta-backend/files/4348661/s20160910_00078_450_reduced.sdf.zip)

however, a beta tester's sdf image (attached) shows up in the file list and if we click it, the backend will crash.
CARTA thinks it is an HDF5 image.
<img width="960" alt="disconnect" src="https://user-images.githubusercontent.com/20819712/76955969-22c62d00-694e-11ea-9505-df3622a238e7.png">
[iext.sdf.zip](https://github.com/CARTAvis/carta-backend/files/4348668/iext.sdf.zip)

**Comment by veggiesaurus** [comment] 2020-03-18 11:26
SDF files _are_ HDF5 underneath, so isn't this a duplicate of #452?

**Comment by kswang1029** [comment] 2020-03-18 11:29
Hmm, don't know SDF is HDF5 underneath. Then yes, it is a duplicate of #452. Not sure why in the first example, it was not detected as an HDF5 image.

I am closing this issue now.

**Closed as completed** 2020-03-18 11:30 UTC
Labels: bug

**Comment by veggiesaurus** [comment] 2020-03-18 11:33
> Hmm, don't know SDF is HDF5 underneath. Then yes, it is a duplicate of #452. Not sure why in the first example, it was not detected as an HDF5 image.
> 
> I am closing this issue now.

is it possible that SDF can have multiple container formats? Can you verify that it doesn't break when using `dev`, since #452 is fixed there

**Comment by kswang1029** [comment] 2020-03-18 11:36
with dev, I do still see the sdf image on the file list but it cannot be loaded. The backend does not crash so we are good.
