### ISSUE TITLE
[file header info] standard FITS header

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#13] opened 2018-12-07 03:25 UTC
It is good to have the displayed header in the file browser to be consistent with FITS header structure. For different image formats, a unified FITS header display is preferential. (c.f. asiaa backend, or ds9)

update: we require a unified standard FITS header for all types of images so that the frontend can process the header in a simple/unified way. For example, while plotting a beam, we found in some cases, BMAJ/BMIN is in arcsec, and in some cases, it is in degree and it is not easily to tell. As a result, the plotted beam size is not correct.

Update:
M100_12m_CO_central.image.miriad (MIRIAD)
M100_12m_CO_central.image.mom0 (CASA)
M100_12m_CO_central.image.mom0.fits (FITS)
The above three images have identical beam size which is 3.46" X 2.37", 89.6784 deg

From their headers
Format		BMAJ		BMIN		BPA	       CUNIT1  CUNIT2
MIRIAD		3.46104		2.36778		89.6784	rad		rad
CASA		3.46104		2.36778		89.6784	rad		rad
FITS		0.000961399	0.000657717	89.6784	deg		deg

==> FITS's BMAJ and BMIN are in deg
==> MIRIAD's and CASA's BMAJ and BMIN are in arcsec

**Comment by pford** [comment] 2019-08-21 17:50
BMAJ and BMIN are converted to deg for CASA and MIRIAD image types (checking HDF5), does anything else need to be done for this issue?

**Comment by kswang1029** [comment] 2019-08-21 23:41
Could we include comments too? For example,
`VELREF  =                  257 /1 LSR, 2 HEL, 3 OBS, +256 Radio`
Currently anything after / is not included and we just see
`VELREF = 257`

**Comment by pford** [comment] 2019-11-27 18:23
I have implemented FITS headers with comments in pam/file_list_fixes branch.  However, when I tried to format the keyword name (8 chars left-aligned) and value (30 chars right-aligned) according to the FITS format, the frontend/AST library could not process the headers, so I reverted to no whitespace in the name and string value as before.

Also, the frontend will need to be modified to remove the comments, e.g. Render Config Widget heading has "Frequency (LSRK / Spectral reference frame)"  and the spatial profile axis is labeled "Value (Jy/beam / Brightness (pixel) unit)".

**Comment by pford** [comment] 2019-12-04 17:56
Included in pull request #387

**Comment by pford** [comment] 2019-12-05 16:50
Uses casacore::ImageFITSConverter::ImageHeaderToFITS for standard FITS header.  Merged into dev.

**Comment by kswang1029** [comment] 2019-12-11 01:26
@pford Mostly looking good. 👍 
Some minor suggestions:
1) in the file info, "Celestial frame = J2000" should be "Celestial frame = FK5, J2000" if "EQUINOX = 2000.0". We will need to display "RADESYS, EQUINOX" keyword. The two common cases would be "FK5, J2000" and "FK4, B1950". The exact number depends on "EQUINOX". If it is "RADESYS = ICRS", we simply display "Celestial frame = ICRS".
2) in the header part, "DATE = 2019-12-11T01:05:33.335000 / Date FITS file was written
" always points to the date and time when FILE_INFO_REQUEST is triggered, which is quite misleading. If this is a limitation due to how FITS header is formed, shall we remove this entry to avoid confusion?
3) for the hdf5 header (@confluence @veggiesaurus comments?), there are some repeated keywords/info at the bottom few lines such as:
SIMPLE = T
EXTEND = T
ORIGIN = CASA 4.5.2-REL (r36115)
SCHEMA = 0.2
HDF5CONV = hdf_convert
CONVVERS = 0.1.7
The top part shows:
SCHEMA_VERSION = 0.2
HDF5_CONVERTER = hdf_convert
HDF5_CONVERTER_VERSION = 0.1.7
4) floating point numbers are displayed as "%.6f". Shall we use "%.12E" to be consistent with ds9? This could avoid truncation error if happens. For integer (e.g. NAXIS), we keep it as integer.
5) with the test server, set_referenceFrames contains a set of images with different "SPECSYS". However, in the file info, "Spectral frame" does not show consistent results.

**Comment by kswang1029** [comment] 2019-12-11 01:46
@jott3077 @arusstaylor @low-sky if you have time, could you check the new format of displayed header and file info are correct and consistent? You may use http://carta.asiaa.sinica.edu.tw/frontend/dev/?socketUrl=wss://carta.asiaa.sinica.edu.tw/socketdev
Thanks for your help.

**Comment by veggiesaurus** [comment] 2019-12-11 06:42
> 3. for the hdf5 header (@confluence @veggiesaurus comments?), there are some repeated keywords/info at the bottom few lines such as:
>    SIMPLE = T
>    EXTEND = T
>    ORIGIN = CASA 4.5.2-REL (r36115)
>    SCHEMA = 0.2
>    HDF5CONV = hdf_convert
>    CONVVERS = 0.1.7
>    The top part shows:
>    SCHEMA_VERSION = 0.2
>    HDF5_CONVERTER = hdf_convert
>    HDF5_CONVERTER_VERSION = 0.1.7

I've checked, and those headers only occur once in the actual HDF5 file, so I'm not sure where the additional header entries are coming from. Which file are you testing?

> 4. floating point numbers are displayed as "%.6f". Shall we use "%.12E" to be consistent with ds9? This could avoid truncation error if happens. For integer (e.g. NAXIS), we keep it as integer.

I think that's probably a frontend issue, if the header values are being sent there as floats

**Comment by kswang1029** [comment] 2019-12-11 06:46
@veggiesaurus set_QA/M17_SWex.hdf5

**Comment by arusstaylor** [comment] 2019-12-11 10:45
Looks ok to me.  I don't see any issues.  I would though like to have the creation date of the file listed in the file information window.

**Comment by jott3077** [comment] 2019-12-11 21:30
would it be possible to show the velocity doppler definition (radio, optical) also in the 'file information'?

I am also looking at the M100_combine_CO_cube.imaging.mom0.pbcor 
and  
M100_combine_CO_cube.imaging.mom0.pbcor.fits 
where I assume one is just the fits version of the other CASA image. 

There are differences in the header. Spectral axis moves between 3 and 4 but also the CRVAL numbers are different:

fits image: 
CTYPE3 = FREQ
CRVAL3 = 114732897321.199997
CDELT3 = -1922516.709869
CRPIX3 = -8.000000
CUNIT3 = Hz

CASA image:
CTYPE4 = FREQ
CRVAL4 = 114732897321.234528
CDELT4 = -1922516.709869
CRPIX4 = -8.000000
CUNIT4 = Hz

both headers have the same frame/doppler definition, so the frequencies should be the same too.

**Comment by jott3077** [comment] 2019-12-11 21:31
it seems not to be possible to open the miriad file that is mentioned in the ticket description

**Comment by kswang1029** [comment] 2019-12-12 02:10
your test images are at set_QA/images-velocity

please let me know if those are sensitive data, then I will remove it.

**Comment by kswang1029** [comment] 2019-12-12 02:40
> fits image:
CTYPE3 = FREQ
CRVAL3 = 114732897321.199997
CDELT3 = -1922516.709869
CRPIX3 = -8.000000
CUNIT3 = Hz

> CASA image:
CTYPE4 = FREQ
CRVAL4 = 114732897321.234528
CDELT4 = -1922516.709869
CRPIX4 = -8.000000
CUNIT4 = Hz

Looking at the values here I wonder if this is due to the fits converter. In this case, the error is tiny.

**Comment by jott3077** [comment] 2019-12-12 17:24
Even if they are tiny we should understand where they come from. There should be no reason that they are different and there could be cases where it makes a big difference. Could indeed be the converter and not CARTA. @kswang1029 Can you check the miriad image that is unavailable right now, too?

**Comment by pford** [comment] 2019-12-12 18:05
With the current branch (pull request pending), both images will show CRVAL = "1.147329e+11", CDELT = "-1.922517e+06" in the header strings.  The numerical values are CRVAL = 114732897321.23453 (CASA), 114732897321.2 (FITS) and CDELT = -1922516.7098693848 (CASA), -1922516.709869 (FITS).

M100_12m_CO_central.image.miriad will show file info in the branch.  The issue is that the 3D image has no headers for the third axis: CTYPE3, CRVAL3, CDELT3, CRPIX3, and CUNIT3 are missing.  So the image CoordinateSystem only has 2 pixel axes but the image shape has 3 dimensions.

**Comment by pford** [comment] 2019-12-12 18:18
@arusstaylor I have named the header DATE -> HDF5_DATE since the FITS header converter replaces DATE with its own current date value, as noted.  CARTA reads the HDF5 headers in order to create the CartaHdf5Image, so it can retain this value.  There is no way I can find to capture the DATE for the other image types.

DATE is a bit confusing; from what I can tell, if an image with a DATE header is converted to HDF5, the DATE header in the HDF5 file retains that date, but if the source image has no DATE then the HDF5 file DATE is set to the date of the HDF5 conversion.

**Comment by pford** [comment] 2019-12-12 22:14
Changes in response to testing merged into dev.

**Comment by pford** [comment] 2020-01-02 17:42
Improvements merged into dev in PR #410 : use native type for spectral axis, use .12E format for float headers.

**Closed** 2020-04-22 14:11 UTC
Labels: enhancement, ready to test
