### ISSUE TITLE
back end disconnects on file load error

### ISSUE THREAD

**Issue by arusstaylor** [CARTAvis/carta-backend#441] opened 2020-02-19 14:16 UTC
I am having issues where a problem with a file load is leading to a disconnection of the backend.    It would be better if there as a more graceful handling when there is a problem with loading a file.  Better for an error message to be sent to the front end user "File Error", and the backend to stay connected.

**Comment by kswang1029** [comment] 2020-02-19 14:18
this feels like a backend crash. Which image is it?

**Comment by arusstaylor** [comment] 2020-02-19 14:20
It is a badly formed hdf5 file on the ILIFU systems.  We discovered after the fact that the file is incorrectly formatted.  

Russ

**Comment by veggiesaurus** [comment] 2020-03-04 07:59
duplicate of #452

**Closed as completed** 2020-03-04 07:59 UTC
Labels: bug
