### ISSUE TITLE
Regex causes seg fault with 6000-point polygon

### ISSUE THREAD

**Issue by pford** [CARTAvis/carta-backend#649] opened 2020-10-23 22:15 UTC
A std::regex issue when importing a CRTF polygon region with as many as 6000 points causes a seg fault in the backend.  This needs to be fixed in the casa6 imageanalysis RegionTextParser, then update the casa6 commit in carta-casacore.

**Comment by pford** [comment] 2020-10-23 23:05
Increased story points to 5 since the CRTF change will likely involve validation testing with the casa viewer, adding another layer of repo management.  Like casaplotms, the casaviewer is in its own repo with casa6 as a submodule.

**Comment by pford** [comment] 2022-02-24 16:36
casa6 PR has been merged

**Comment by kswang1029** [comment] 2022-03-08 05:55
confirmed that with https://github.com/CARTAvis/carta-casacore/pull/17 the issue is fixed in CARTA.

**Closed as completed** 2022-03-09 13:19 UTC
Labels: bug
