### ISSUE TITLE
backend crash when opening set_QA/supermosaic.10.hdf5 

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#212] opened 2019-05-10 03:22 UTC
this happens with the dev backend. 

h5dump -H log is attached.

[https://app.zenhub.com/files/160788905/f66a726b-2c5d-4e43-a475-1547c79fcb62/download](https://app.zenhub.com/files/160788905/f66a726b-2c5d-4e43-a475-1547c79fcb62/download)

update with testing with images in set_HDF5
h_m51_b_s05_drz_sci.hdf5 --> crash
orion_12co_hera.hdf5          --> crash

Noticed that when opening the hdf5 images in set_HDF5, it takes few to several seconds to open images  which are not that big in xy dimension. The same images in FITS are opened much faster.

**Comment by pford** [comment] 2019-05-10 14:27
It works with the hdf5 images I have.  I cannot scp this image from asiaa (permission denied), sent message to Anthony.

The backend is reading the header attributes, creating a casacore::Record, then feeding that to a utility to create a casacore::CoordinateSystem.  Will see how I can reuse the headers in FileInfoExtended for hdf5.

**Comment by pford** [comment] 2019-05-13 19:32
The issue was that it was using OBSFREQ for RESTFRQ, but I neglected to convert the OBSFREQ string value to a float.  Also converted FileInfoExtended into casacore::Record for coordinate system rather than reading headers from file again.

**Comment by kswang1029** [comment] 2019-05-15 01:09
@pford Thanks. supermosaic.10.hdf5 works now. However, the issue remains for 
set_HDF5/h_m51_b_s05_drz_sci.hdf5
set_HDF5/orion_12co_hera.hdf5

Guessing again it is header issue.

**Comment by pford** [comment] 2019-05-15 15:43
The orion dataset works in my developer build on the dev branch.  The m51 dataset seg faults in wcslib.

**Comment by pford** [comment] 2019-05-15 19:59
The problem is that the hdf5 converter (incorrectly) makes all header items in the hdf5 image a string value.  CARTA has to figure out which ones to convert from string to bool, int, or float so that the keyword/value pairs can be used to make a coordinate system.  I am fixing this for the test datasets but it may trip up on other hdf5 header keywords in the future.

**Comment by veggiesaurus** [comment] 2019-05-15 21:23
This is done to maintain round trip compatibility with FITS, where the header entries are all strings.

**Comment by pford** [comment] 2019-05-15 22:23
Not according to the papers cited by wcslib http://www.atnf.csiro.au/people/mcalabre/WCS/
e.g. table 8 on page 14 of "Representations of world coordinates in FITS"
http://www.atnf.csiro.au/people/mcalabre/WCS/wcs.pdf

**Comment by veggiesaurus** [comment] 2019-05-16 03:22
The FITS header itself is text based, so the entities are still stored as strings in the actual file.

**Comment by pford** [comment] 2019-05-17 14:52
From what I can tell, FITS parses the entire header as a string, but there is still a difference between string and numeric values.
ERROR: string hdf5 attribute:
`"BITPIX   = '-32'" // Keyword Error: name = BITPIX of type STRING and value '-32'`
CORRECT: int hdf5 attribute:
`"BITPIX   = -32"`
so the backend has to figure out from which entries to remove the single quotes indicating a string value.

**Comment by veggiesaurus** [comment] 2019-05-17 15:45
I would suggest we therefore fix the HDF5 converter to keep the `'` when parsing the FITS header.

**Comment by pford** [comment] 2019-05-17 19:55
All set_HDF5/ and set_QA/ HDF5 images seem to work now.  I occasionally crashed the backend while testing with CARTA mix 'n match but if I restart the backend and reopen the image it is okay.  Possibly a result of issue #19 (was: [image close] backend crash when close file but threads are still running.)?

**Comment by veggiesaurus** [comment] 2019-05-20 09:49
supermosaic is still crashing for me on `dev` branch. Output is 
```
2019-05-20 09:48:26	WARN	FITSCoordinateUtil::fromFITSHeader	Zero or no rest frequency provided for velocity axis.
Error opening HDF5 image: TabularCoordinate - start and end values in table must differ
ERROR: xy region type RECTANGLE failed: Matrix<T>::row - row < 0 or > end
```

**Comment by pford** [comment] 2019-05-20 15:13
It works for me, I can get stats (image, rectangle region) and z-profile (rectangle region) with macos 10.13 and docker ubuntu:```2019-05-20 15:11:00	INFO	FITSCoordinateUtil::fromFITSHeader	Header
2019-05-20 15:11:00	INFO	FITSCoordinateUtil::fromFITSHeader+	OBSFREQ =   1.420406000000E+09                                                  
2019-05-20 15:11:00	INFO	FITSCoordinateUtil::fromFITSHeader+	was interpreted as
2019-05-20 15:11:00	INFO	FITSCoordinateUtil::fromFITSHeader+	RESTFRQ =   1.420406000000E+09```

**Comment by veggiesaurus** [comment] 2019-05-20 16:51
Have tested again with `dev`, still getting the same crash. It's crashing in line 233 of `Region.cc`, because `_coord_sys.nPixelAxes()` is returning `0`. 
Very odd. Tried installing the latest commit to `master` of casacore, but same thing happens

**Comment by pford** [comment] 2019-05-20 17:31
I am also using the latest version of master and carta-backend dev, works for me.

Are you testing your own build?  Are you using version 5.x of wcslib?  casacore does not seem to work with 6.2.
```
# ldd carta_backend | grep coord
	libcasa_coordinates.so.3 => /usr/local/lib/libcasa_coordinates.so.3
# ldd /usr/local/lib/libcasa_coordinates.so | grep wcs
	libwcs.so.5 => /usr/lib/x86_64-linux-gnu/libwcs.so.5
```

**Comment by veggiesaurus** [comment] 2019-05-20 17:51
also using 5.x of wcslib. Will try track down the problem tomorrow. It's rather odd.

**Comment by pford** [comment] 2019-05-20 18:28
// Copying constructor (copy semantics)
CoordinateSystem(const CoordinateSystem &other);

You should not be getting `Zero or no rest frequency provided` if RESTFRQ or OBSFREQ are defined.

**Comment by kswang1029** [comment] 2019-05-22 01:21
@pford I tried all HDF5 images we have on the server and all work now. (will automize this image scan test)
@veggiesaurus do you still encounter problems with supermosaic?

**Comment by veggiesaurus** [comment] 2019-07-09 18:41
I think we can close this. There were issues with the older convertor producing inconsistent headers, this should be sorted out. Since IDIA-HDF5 is just used internally at the moment (and we can choose to limit which version of the schema is supported by CARTA), this is not a problem.

**Closed by veggiesaurus** 2019-07-09 18:41 UTC
Labels: bug, ready to test
