### ISSUE TITLE
CARTA hangs in file info gathering step

### ISSUE THREAD

**Issue by jott3077** [CARTAvis/carta-backend#431] opened 2020-01-30 16:38 UTC
I have a directory with manny CASA images. When I browse through, look at some, then go back and load others, at some point while just checking the file info, CARTA 1.2.2 hangs. When I then go back to 'load' The 'loading file' message also keeps on spinning.

**Comment by veggiesaurus** [comment] 2020-03-04 11:00
@arusstaylor does this seem similar to what you experienced on carta-testing?

**Comment by arusstaylor** [comment] 2020-03-04 11:27
The load file message and spinning is the same, but it happened to me directly on startup when the file load tool comes up automatically.   So not related to any specific action with the file load tool.

**Comment by veggiesaurus** [comment] 2020-03-04 11:41
> The load file message and spinning is the same, but it happened to me directly on startup when the file load tool comes up automatically. So not related to any specific action with the file load tool.

Your backend log file seemed to indicate that there were other sessions still running, so perhaps one of those other sessions was causing an issue :thinking:

**Comment by keflavich** [comment] 2020-06-27 15:09
I'm seeing the same issue on CARTA 1.3.1.  Is there any way to load a file _without_ using the file browser?

**Comment by jott3077** [comment] 2020-06-27 17:39
try carta <imagename>


On June 27, 2020 09:09:30 Adam Ginsburg <notifications@github.com> wrote:
>
> I'm seeing the same issue on CARTA 1.3.1. Is there any way to load a file 
> without using the file browser?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or unsubscribe.


Sent with AquaMail for Android
https://www.mobisystems.com/aqua-mail

**Comment by keflavich** [comment] 2020-06-27 19:43
That had no effect - I still see "No file loaded".

However, running carta & specifying the file name does work if I start from a directory that contains no .image files.

I suggest *not* loading the file browser at startup.  In folders containing large numbers of .images - which as you can see from both @jott3077 and my use cases, is common if not the default - CARTA simply fails to load.

**Comment by kswang1029** [comment] 2020-06-29 05:25
I tried 
`carta carta_lots_files` 
to launch CARTA with a custom folder "carta_lots_files" which contains 1000 fits images, 1000 miriad images (folder image), 1000 casa images (folder image), 1000 CRTF files, and 1000 plain text files. It works although it takes some time to load (with MBP SSD). 

@keflavich in your case, what does your folder look like?

**Comment by veggiesaurus** [comment] 2020-06-29 07:57
> I suggest _not_ loading the file browser at startup. In folders containing large numbers of .images - which as you can see from both @jott3077 and my use cases, is common if not the default - CARTA simply fails to load.

This is configurable in the preferences dialog: Preferences -> Global -> Auto-launch file browser. We are also working on improving parse speed for single-file images (FITS, Miriad, etc). Not sure if this will also translate to improved speeds for CASA images, though. 


> with MBP SSD

SSDs have _much_ higher (100x) random read speeds, which is what is governing the speed at which these files are parsed.

**Comment by kswang1029** [comment] 2020-06-29 08:14
@veggiesaurus i will try again with much more files!

**Comment by veggiesaurus** [comment] 2020-06-29 08:29
> @veggiesaurus i will try again with much more files!

Could you try with files on an external hard drive or something? A HDD-based Lustre would also be a good option for testing

**Comment by kswang1029** [comment] 2020-06-29 08:32
ok. I will try again with an external 5400rpm 2.5” HDD. For lustre, our demo server has such kind of folder and it is very slow...

**Comment by keflavich** [comment] 2020-06-29 11:39
In my case, I have 455 images cube images (x9 for weight, psf, residual, sumwt, model, pb, mask, image.pbcor) and 827 continuum images (x22 for the associated stuff).  So, 22,289 files, summing to probably 10-50 TB (it'll take a while to sum that up).  Obviously this is some sort of network drive, almost certainly with spinning disks, so access times are pretty abysmal. 

I'll try disabling the autolaunch, but if I do that, how can I open files?  Is there a way to open files from within CARTA w/o the browser, or do I have to stick to whatever file(s) I open from the cmdline?

**Comment by kswang1029** [comment] 2020-06-30 03:52
I tried a folder living in the external HDD (2.5" 5400rpm, USB type-C), which contains
1) 5000 casa images
2) 5000 fits images
3) 5000 miriad images
4) 5000 CRTF files
5) 5000 plain text files

Firstly I cd to the external directory "/Volumes/WD_2TB_backup/carta_lots_files" and launch CARTA via command line without any arguments. It loads successfully (slow....). 

Will try with a network storage to see if I can reproduce the issue.

**Comment by veggiesaurus** [comment] 2020-06-30 06:53
> It loads successfully (slow....).

How slow is "slow"? 

@keflavich I'm wondering if something is actually causing the CARTA backend to crash or get into a deadlock. Could you attach your most recent log file? (usually found in `~/CARTA/log`)

**Comment by kswang1029** [comment] 2020-06-30 06:58
> How slow is "slow"?

in my case, 1 min 29 sec......

**Comment by keflavich** [comment] 2020-06-30 11:48
I have also had successful loads in ~1-2 minutes in directories with a few hundred images.  I suspect the network drive is making this much slower.  Does file size matter?

One thing that's frustrating is, if I accidentally navigate to one of these big directories, CARTA is "dead" either for minutes (for a medium-size directory) or forever (for a huge one).  Is there any way to enable a user to pass an Interrupt (control-C) to the file browser to force it to give up?

**Comment by markccchiang** [comment] 2020-12-07 08:12
Is it ok that we show a progress bar while gathering the file list? And there is a cancel button that allows us to interrupt this process.

**Comment by veggiesaurus** [comment] 2020-12-07 08:35
We should rather improve this. If we just read the magic number instead of
all the fits info things should be much faster

**Comment by kswang1029** [comment] 2020-12-07 09:20
Yes I think we better implement the magic number approach first and see if latency is still an issue then decide whether or not having a progress bar when the total number of files is above a certain threshold.

**Comment by markccchiang** [comment] 2020-12-07 14:58
Will set a magic number for the file list. I think we can add an option that users can choose whether to read the rest of the files if the total number of files is above a magic number.

**Comment by markccchiang** [comment] 2020-12-07 15:12
Oh, I misunderstood it. @kswang1029 just informed me of the detailed way.

**Comment by pford** [comment] 2020-12-07 17:39
Issue #357 changes the file browser to determine the FITS image type but not the HDU names/types until file info is requested.  This branch is ready to test once we support this in the frontend.

For files, the casacore::ImageOpener checks for (1) filename = name.image and name.descr exists (GIPSY), (2) read in a buffer, begins with "SIMPLE = T" regex (FITS), and (3) H5Fis_hdf5 returns true (HDF5).  I suppose just reading in a buffer and checking the magic number for FITS/HDF5 would speed this up.

For directories, the casacore::ImageOpener checks if the directory (1) contains file "imageconcat.json" (IMAGECONCAT), (2) contains file "imageexpr.json" (IMAGEEXPR), (3) contains file "table.info" with "Type = Image" (AIPSPP which is CASA) or "Type = Component List" (COMPLISTIMAGE), or (4) contains files "header" and "image" (MIRIAD).

**Comment by pford** [comment] 2020-12-07 18:51
@markccchiang see Util.cc GetMagicNumber(filename)

**Comment by pford** [comment] 2020-12-07 20:11
Looking at the original issue description, I tried this in mix 'n match and it looked like a threading issue when the image loading is slow.

While an image is loading, the file browser remains active so you can click on other images in the list which requests file info for each one.  Eventually you just get the "Loading file info..." spinner because the backend is handling the OPEN_FILE and previous FILE_INFO_REQUESTs in order (as shown in the dev console) but the file browser/frontend is waiting for the FILE_INFO_RESPONSE for the currently selected image.  CARTA eventually closes the file browser and shows the image but you see all of the FILE_INFO_RESPONSE messages in the console after OPEN_FILE_ACK.  We may actually need a mechanism to discard previous file info requests and only process the latest one, or disable file browser interaction after "Load" is clicked.

**Comment by veggiesaurus** [comment] 2020-12-08 12:40
> or disable file browser interaction after "Load" is clicked.

We currently disable the "Load" button once you've clicked it. But we should disable it while waiting for file info, and perhaps we should disable clicking on a file if still waiting for file info?

**Comment by markccchiang** [comment] 2021-01-06 03:56
I have created a test branch [mark/431_checks_magic_number_for_fits_hdf5](https://github.com/CARTAvis/carta-backend/tree/mark/431_checks_magic_number_for_fits_hdf5), which uses magic numbers to identify FITS or HDF5 files. And also avoid calling the `casacore::ImageOpener::imageType()` function twice. Tested performances of the new code on the ACDC server. The file list gathering speed for CASA, MIRIAD, and FITS files are increased by 10%, 3%, and 14%, as shown below:
![time-vs-filetype](https://user-images.githubusercontent.com/5379602/103727113-72790080-5015-11eb-9c48-1da935dfc3ca.png)
Is it acceptable? Or we may apply the progress bar and an interruption function?

**Comment by veggiesaurus** [comment] 2021-01-06 07:11
> Is it acceptable? Or we may apply the progress bar and an interruption function?

@markccchiang presumably this is still using the old method of populating the FITS HDU for each file, since https://github.com/CARTAvis/carta-frontend/pull/1274 and https://github.com/CARTAvis/carta-backend/pull/672 aren't merged yet. I think we need to wait for that be merged before doing any meaningful performance tests.

**Comment by markccchiang** [comment] 2021-01-12 08:13
I have updated the [mark/431_checks_magic_number_for_fits_hdf5](https://github.com/CARTAvis/carta-backend/tree/mark/431_checks_magic_number_for_fits_hdf5) and merged with the new dev branch. Tested performances of the modified code and compared it to the dev branch on the ACDC server. Used the command `sync; echo 3 > /proc/sys/vm/drop_caches` to clear the cache and repeated the test. But I found it sometimes has a large variation on the performance. The average of the file list gathering speed for CASA, MIRIAD, FITS, FITS w/ HDUs, and HDF5 files are shown below:
![time-vs-filetype](https://user-images.githubusercontent.com/5379602/104285324-6e098780-54ee-11eb-8164-2b3af2c4bd79.png)
@kswang1029 has an idea to increase the speed of gathering a CASA file list, which is by only checking the head of the `CASA_file.image/table.info` file. If it could not cause problems, I will try this way.

**Comment by veggiesaurus** [comment] 2021-01-12 10:50
@markccchiang this is a nice speedup for FITS/HDF5. I wonder how much of it is down to only checking the file type _once_, and how much is down to the other changes. casacore seems to basically be doing a magic number check as well. It reads a little more data (2.5 kB, I think) but this probably makes no difference

**Comment by veggiesaurus** [comment] 2021-01-12 10:56
I do think we should benchmark this on a local hard drive and SSD, so that we can do a proper cache clearing. lustre will definitely result in erratic performance.

**Comment by kswang1029** [comment] 2021-01-12 11:16
@ajm-asiaa if you can make a desktop build I can try with my probable HDD.

**Comment by ajm-ska** [comment] 2021-01-12 11:40
@kswang1029 OK. I'll make one shortly with the `mark/431_checks_magic_number_for_fits_hdf5` branch.

**Comment by kswang1029** [comment] 2021-01-14 05:04
Thanks to @ajm-asiaa for making a desktop build for testing with an external 2.5" HDD. I prepared a new set of images with each type 5000 copies. Before the measurements, I reboot my laptop then reconnect the HDD. I used the timestamps of the messages FILE_LIST_REQUEST and FILE_LIST_RESPONSE to get the elapsed time. I repeated the test with v1.4 three times and Mark's branch two times, with a system reboot and HDD remount in between. The results (in sec) are

<img width="454" alt="Screen Shot 2021-01-14 at 12 56 57 PM" src="https://user-images.githubusercontent.com/20819712/104547110-b64cb500-5668-11eb-8df2-90759ddcf868.png">

It appears that only "FITS with multiple HDUs" got a performance boost by ~2.4x. Others perform the same. Note that I saw large variations in FITS. Not sure what the root cause is....

**Comment by veggiesaurus** [comment] 2021-01-14 13:40
> It appears that only "FITS with multiple HDUs" got a performance boost by ~2.4x. Others perform the same. Note that I saw large variations in FITS. Not sure what the root cause is....

That's quite surprising. I expected a much larger improvement :thinking:

**Comment by kswang1029** [comment] 2021-01-14 15:03
Would it be io bounded by the slow 5400rpm HDD?

**Comment by markccchiang** [comment] 2021-01-14 15:25
I am doing the same test on my local computer and with a local hard drive. Roughly get similar results. If it is not due to my code problem, should we apply an interruption function?

**Comment by markccchiang** [comment] 2021-01-19 07:36
While gathering a file list, the method `casacore::ImageOpener::imageType` will be called twice. They are on the [FileListHandlet.cc, line 132](https://github.com/CARTAvis/carta-backend/blob/dev/src/FileList/FileListHandler.cc#L132), and from the [FillFileInfo function](https://github.com/CARTAvis/carta-backend/blob/dev/src/FileList/FileListHandler.cc#L166). I guess there is already a cache generated after the first call, it only needs a very short time to pass the second call. So there is almost no performance difference. I created two test branches [mark/431_apply_ImageOpener_once_timer](https://github.com/CARTAvis/carta-backend/tree/mark/431_apply_ImageOpener_once_timer) and [mark/431_apply_ImageOpener_twice_timer](https://github.com/CARTAvis/carta-backend/tree/mark/431_apply_ImageOpener_twice_timer) to measure differences of time spends for these two steps (on the local dick). The results are shown below:
![截圖 2021-01-18 下午11 14 54](https://user-images.githubusercontent.com/5379602/104997916-5d648e80-5a65-11eb-9587-d3a16cd67a84.png)

Using magic numbers to identify FITS or HDF5 images instead of `casacore::ImageOpener::imageType` also got similar performance results, which are measured by the branch [mark/431_checks_magic_number_for_fits_hdf5_timer](https://github.com/CARTAvis/carta-backend/tree/mark/431_checks_magic_number_for_fits_hdf5_timer). Looks like the time spend to get a magic number dependents on the file type. So my current thinking is that there is no room to improve the performance of getting a file list.

**Comment by kswang1029** [comment] 2021-01-19 07:49
If there is no room for improving, I would suggest we implement
1) cancellation
2) periodic progress report (every 2s) _only if_ it takes more than 5s for parsing

**Comment by veggiesaurus** [comment] 2021-01-19 07:51
> If there is no room for improving, I would suggest we implement
> 
> 1. cancellation
> 2. periodic progress report (every 2s) _only if_ it takes more than 5s for parsing

These will require frontend changes as well. Who should we assign them to? We also shouldn't make the progress bar _blocking_, you may well want to select a file while the rest of the list is still appearing

**Comment by kswang1029** [comment] 2021-01-19 07:58
or..... we implement progressive update just like catalog table? 
UPDATE: this may be a bad idea as users cannot see the full list initially thus the filter box is less useful.

**Comment by pford** [comment] 2021-01-19 16:24
From a software standpoint (Don't Repeat Yourself), I think it is still worth doing to pass the image type from FileListHandler to FileInfoLoader rather than have both determine the type.  This is very easy to implement in the code.

**Comment by markccchiang** [comment] 2021-01-27 04:17
I have prepared a backend branch [mark/431_file_list_interruption](https://github.com/CARTAvis/carta-backend/tree/mark/431_file_list_interruption) and a protobuf branch [mark/stop_getting_file_list](https://github.com/CARTAvis/carta-protobuf/tree/mark/stop_getting_file_list), which allow reporting the progress of gathering a file list and cancellation. The progress of a file list will shown after 5 secs and update it every 2 secs.

Five event types are added in the protobuf:
![截圖 2021-01-29 上午10 19 35](https://user-images.githubusercontent.com/5379602/106223048-ac57b400-621b-11eb-9adf-4c1cae8c8feb.png)

The definitions of the file, region, and Catalog list progress messages are:
![截圖 2021-01-29 上午10 20 18](https://user-images.githubusercontent.com/5379602/106223173-e45ef700-621b-11eb-992f-1cd4d46e68e2.png)

**Comment by markccchiang** [comment] 2021-01-29 02:30
I have updated a backend branch [mark/431_file_list_interruption](https://github.com/CARTAvis/carta-backend/tree/mark/431_file_list_interruption) and a protobuf branch [mark/stop_getting_file_list](https://github.com/CARTAvis/carta-protobuf/tree/mark/stop_getting_file_list), and add the same functionality for the Catalog file list. The UML plots for the file, region and Catalog list processes are
![file_list_uml](https://user-images.githubusercontent.com/5379602/106223697-e70e1c00-621c-11eb-9efe-56a96746a3f0.png)
![catalog_uml](https://user-images.githubusercontent.com/5379602/106223706-eb3a3980-621c-11eb-9c63-0f3f5b82aa5f.png)

**Comment by kswang1029** [comment] 2021-01-29 02:37
@markccchiang just to confirm, when users cancel the file list request, the frontend should show the file list _just before_ users made a file_list_request of the folder. That is, after STOP_FILE_LIST, the backend returns FILE_LIST_RESPONSE which should be the file list before FILE_LIST_REQUEST. Does the above description fit your design?

**Comment by markccchiang** [comment] 2021-01-29 03:34
@kswang1029 After the STOP_FILE_LIST, the backend returns FILE_LIST_RESPONSE which is the *partial* file list with respect to the FILE_LIST_REQUEST.

**Comment by kswang1029** [comment] 2021-01-29 03:37
@markccchiang then we will need to change this. Assuming a file list request of /A/B/C is made and then cancelled, we should deliver the file list of /A/B 

One exception needs to be considered: if it is not possible to go one level back due to the constrain set by $root, then we need to let the file list generation complete (ie no cancellation is allowed).

**Comment by veggiesaurus** [comment] 2021-01-29 03:41
> @markccchiang then we will need to change this. Assuming a file list request of /A/B/C is made and then cancelled, we should deliver the file list of /A/B 

Shouldn't we just keep this cached on the front-end? Not sure we need to return anything after the cancellation is sent

**Comment by kswang1029** [comment] 2021-01-29 03:42
@veggiesaurus if the frontend cached /A/B, that would be good and efficient. Then when cancel request is made, the backend does not need to return anything.

**Comment by veggiesaurus** [comment] 2021-01-29 03:44
> @veggiesaurus if the frontend cached /A/B, that would be good and efficient. Then when cancel request is made, the backend does not need to return anything. 

Yes, I think that's probably the best solution

**Comment by markccchiang** [comment] 2021-01-29 03:45
> > @veggiesaurus if the frontend cached /A/B, that would be good and efficient. Then when cancel request is made, the backend does not need to return anything.
> 
> Yes, I think that's probably the best solution

OK.

**Closed as completed** 2021-06-04 07:27 UTC
Labels: bug, requiring frontend
