### ISSUE TITLE
Spectral profile test with various stokes fails: Hdf5Loader returns same stats

### ISSUE THREAD

**Issue by zarda** [CARTAvis/carta-backend#247] opened 2019-06-14 01:29 UTC
https://github.com/CARTAvis/carta-backend/blob/3253c1b94fc4e7c0e6252ee220420b838d78cb58/Session.cc#L788
About updating the profile data, the backend will check if the frontend has already set a cursor. In case of region operation, is this a must to check? At current ICD backend test, the tester needs to set both region and cursor so that the profile data updates.

**Comment by pford** [comment] 2019-06-19 20:58
The backend sets up a default cursor region at (0,0) after opening the image, so that it can set requirements for the cursor region before SET_CURSOR has been called.  But it should not send spatial or spectral profiles for the cursor until the frontend has sent SET_CURSOR or SET_REGION with region_id=0 (CURSOR_REGION_ID).  That is the reason for the check, which should not affect any other regions (region_id > 0).

**Comment by zarda** [comment] 2019-06-25 08:57
The testing will fail if the tester does not send SET_CURSOR before changing channel or stokes because no SPECTRAL_PROFILE will response. Is this outcome our expectation? @kswang1029

**Comment by pford** [comment] 2019-06-25 19:59
I increased the timeouts in config.json, then the REGION_SPECTRAL_PROFILE_STOKES test completed.  All tests passed except the set_QA/HH211_IQU.hdf5 mean value for stokes 1 and 2.

I confirmed with my developer build that the spectral profile values are from the Hdf5Loader, not calculated in RegionStats.  In the Chrome dev console, new messages are sent for each stokes but the values are all the same.  When the spectral data is requested for a new stokes value in Hdf5Loader::GetRegionSpectralData, recalculate=false so (I think) the same stats are returned for all three requested stokes.  Editing issue description and reassigning to Adrianna.

**Comment by confluence** [comment] 2019-06-25 22:11
I think the loader doesn't take stokes into account when deciding whether to recalculate the stats -- it only checks whether the region has changed shape or position. Should be an easy fix; I just need to see how best to incorporate this.

**Comment by kswang1029** [comment] 2019-06-26 02:27
> The testing will fail if the tester does not send SET_CURSOR before changing channel or stokes because no SPECTRAL_PROFILE will response. Is this outcome our expectation? @kswang1029

with GUI, we cannot define a region without triggering SET_CURSOR since we have to move cursor on the image. However, from the message point of view, we can define a region directly with SET_REGION, and send SET_SPECTRAL_REQUIREMENTS with that region id. Then we should receive the corresponding SPECTRAL_PROFILE_DATA without SET_CURSOR. 

With the GUI and js console, SET_IMAGE_CHANNEL triggers stream messages including SPECTRAL_PROFILE_DATA without additional SET_SPECTRAL_REQUIREMENTS.

**Closed** 2019-06-27 12:45 UTC
Labels: ICD test failure, question
