### ISSUE TITLE
crash when loading HDF5 image NOT in IDIA schema

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#452] opened 2020-03-04 07:40 UTC
This is reported by a 1.3 beta tester while loading an HDF5 image from simulation.
Test image is attached. 

![carta3](https://user-images.githubusercontent.com/20819712/75856010-65f0ae00-5e2e-11ea-80a6-830363d66082.JPG)
[M0030.h5.zip](https://github.com/CARTAvis/carta-backend/files/4285841/M0030.h5.zip)

**Comment by veggiesaurus** [comment] 2020-03-04 07:50
duplicate of #441?

**Comment by veggiesaurus** [comment] 2020-03-04 07:54
@confluence or @pford could you look at this?

**Comment by kswang1029** [comment] 2020-03-04 07:55
maybe similar. This case is an HDF5 image in a whatever schema. #441 "might" be due to something odd when converting to HDF5 format?

**Comment by veggiesaurus** [comment] 2020-03-04 07:57
no, #441 was also a non-IDIA HDF5 (I checked with @arusstaylor). Perhaps we can close that in favour of this issue, since it's more clearly described.

**Comment by kswang1029** [comment] 2020-03-04 07:58
ok  👍

**Comment by confluence** [comment] 2020-03-04 14:04
I have assigned this to myself; it should be simple to fix.

**Comment by confluence** [comment] 2020-03-04 23:47
Turns out it's not that simple. In our HDF5 image constructor, attempting to create a lattice with a non-existent dataset triggers an exception inside casacore, which should be displayed as an error in the file browser. However, any exception thrown in that constructor before or during the construction of the lattice causes a segfault in the destructor of the lattice member, because the destructor calls `flush`, which calls `flush` on the lattice's file object without checking whether it exists, and at that point the member is still uninitialized. This may be a bug in casacore, given that it prevents an uninitialized lattice from being destroyed, but we can work around it by initializing the lattice in the initializer list of the constructor instead of doing it inside the body. I will create a PR for the fix.

**Closed as completed** 2020-03-05 13:18 UTC
Labels: critical bug

**Comment by kswang1029** [comment] 2020-03-18 11:30
related to https://github.com/CARTAvis/carta-backend/issues/472

**Comment by kswang1029** [comment] 2020-03-18 11:32
and in the dev, it won't crash the backend.
