### ISSUE TITLE
Hard crash when animation messages are received in unexpected order

### ISSUE THREAD

**Issue by veggiesaurus** [CARTAvis/carta-backend#981] opened 2021-12-02 13:35 UTC
@robsimmonds to fill in description shortly...

**Comment by robsimmonds** [comment] 2021-12-07 06:57
I believe the issue is due to something slightly different. I think that if an animation task is still running when a new one is created, the pointer to the animation object in the session object can be left in a bad state. In this case serialising the update of that pointer should resolve this.

**Comment by confluence** [comment] 2022-02-15 12:41
This was fixed in previous commits.

**Closed as completed by confluence** 2022-02-15 12:41 UTC
Labels: bug
