### ISSUE TITLE
moment generator: no progress update or crash

### ISSUE THREAD

**Issue by kswang1029** [CARTAvis/carta-backend#593] opened 2020-08-14 08:07 UTC
in some cases of long calculations, we don't have progress report after the first 5s. And if we cancel the request and request a new one, the backend may crash. 

Backport for v1.4 final

**Comment by markccchiang** [comment] 2020-08-17 04:56
@kswang1029 Is there an example case that can be reproduced? I am trying to fix it.

**Comment by kswang1029** [comment] 2020-08-17 04:59
try set_S255/S255_IR_sci.spw29.cube.I.pbcor.fits
1. enable moment calculations by pressing the generate button directly (using entire cube)
2. when you see the first progress update, press cancel
3. enable a new moment calculations by pressing the generate button directly
4. backend will crash

**Comment by kswang1029** [comment] 2020-08-17 05:01
about the issue of no progress update
try set_HDF5/S255_IR_sci.spw29.cube.I.pbcor.hdf5
1. enable moment calculations by pressing the generate button directly (using entire cube)
2. there is no progress update
3. cancel the calculation and make a new one
4. backend may crash (the root cause might be the same as the one above) threading?

**Comment by kswang1029** [comment] 2020-08-18 05:35
Found a more robust way to reproduce the crash event. It appears that the backend accidentally was working on streaming spectral profile and moment generation at the same time.
1. load a large cube with lots of channels (need profile streaming)
2. lock cursor
3. enable moment calculations and cancel
4. unlock cursor and click the generate button quickly before new cursor profile is streaming.
5. the backend should crash

**Comment by duidae** [comment] 2020-08-20 07:50
about the progress, can turn on the progress message:

![image](https://user-images.githubusercontent.com/25971696/90731443-4aa22e00-e2fc-11ea-84f3-295cf78eb7b7.png)
![image](https://user-images.githubusercontent.com/25971696/90732197-53473400-e2fd-11ea-9574-1a1400e62706.png)


tried set_HDF5/S255_IR_sci.spw29.cube.I.pbcor.hdf5 with my desktop(ubuntu) yesterday, seems no message was sent yet & results in empty progress, and Mark tried with server, there will be progress response, so probably missing progress is due to pending message.

**Comment by markccchiang** [comment] 2020-08-20 08:20
The progress bar for `set_HDF5/S255_IR_sci.spw29.cube.I.pbcor.hdf5` is OK if you test it on the server. However, @duidae tested it on the desktop and not work. It is possible that if the calculation time for a chunk is more than 5 secs, then you will not see the progress report in the first 5 secs.

**Comment by veggiesaurus** [comment] 2020-09-04 08:32
@kswang1029 please confirm this is fixed in the latest `release/1.4` branch

**Comment by kswang1029** [comment] 2020-09-04 10:32
release/1.4 looks fine mostly.

I found a robust way to reproduce the no progress update issue. The backend supplies progress but the frontend does not show it as a progress bar. It can be triggered by loading a large fits thus cursor spectral profiles take time to update. Then move the cursor from the image to the generate button _quickly_ so that before profile starts updating, the generate button can be clicked before it is disabled due to profile streaming. In this case, the moment calculations will wait until the streaming cursor profile finishes. While streaming we see an empty progress bar with the full screen in blocked mode. Then once moment calculation starts at the backend we will see progress update in the js console but somehow the frontend empty progress bar remains empty. As long as we wait long enough so that moment calculation finishes, the empty progress bar will disappear. Things are still normal and functional. 

Not sure what the root cause is and it is from the backend or frontend. 

As you can see how tricky it is to trigger this issue, this is probably not a showstopper of v1.4 release.

**Comment by kswang1029** [comment] 2020-09-04 10:46
btw, as we plan to refactor backend code for 1.5, we can revisit this issue again to see if it is still there.

**Comment by markccchiang** [comment] 2020-09-07 07:46
I am refactoring the moment generator code. @kswang1029 maybe you can test with the branch `mark/refactor_moment_generator` if you have time. So far I can not reproduce the progress problem. But I found it is better for the frontend to disable *all* `generate` buttons if you open multiple moment generator widgets (which are with respect to different regions or cursor) and making a spectral profile in the same time. Otherwise, the enqueued moment tasks will keep going and can not be canceled if you frequently click the `generate` and `cancel` buttons in a short time.

**Comment by markccchiang** [comment] 2020-09-07 07:52
![截圖 2020-09-07 下午3 50 20](https://user-images.githubusercontent.com/5379602/92362125-1d3de880-f122-11ea-8765-f290a3d6f6f8.png)

**Comment by kswang1029** [comment] 2020-09-07 07:58
@markccchiang could you file an issue in the frontend repo with detailed instructions on how to reproduce it? We will need to fix this in 1.5.

**Closed as completed** 2020-09-09 02:56 UTC
Labels: bug, backport
